from collections.abc import Callable
from typing import Protocol, TypeVar

T = TypeVar("T", bound=Callable[..., object])

class ASGIApp(Protocol):
    async def __call__(self, scope: dict[str, object], receive: Callable[..., object], send: Callable[..., object]) -> object: ...

class FastMCP:
    def __init__(self, name: str | None = ..., instructions: str | None = ..., *, host: str = ..., port: int = ..., streamable_http_path: str = ..., json_response: bool = ...) -> None: ...
    def tool(self, description: str = ...) -> Callable[[T], T]: ...
    def custom_route(self, path: str, methods: list[str] | None = ...) -> Callable[[T], T]: ...
    def streamable_http_app(self) -> ASGIApp: ...
